### ISSUE TITLE
could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by LordKayBanks** [jim60105/docker-whisperX#16]
screenshot below:

![image](https://github.com/jim60105/docker-whisperX/assets/24697778/5323c0ce-f402-4d88-b863-8f5c46af4182)

**Comment by jim60105** [comment]
Do you have gpu support for your docker?
Please try again after completing this guide:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by LordKayBanks** [comment]
thanks. i got it working

**Comment by LordKayBanks** [comment]
One more thing, How can I use the large v2 model (mult-language model), so that i dont have to run and download another docker image over and over whenever i need to transcribe for a different language?

**Comment by jim60105** [comment]
On your collab, it did not re-download the align model because it had been downloaded before and the model is stored on the machine.
As for Docker, every time you excute docker run, it will open a new container and its cache is not shared.
You can docker mount the `/cache` folder to solve this problem.

**Comment by jim60105** [comment]
Oh, I think I should add this to the readme.

**Comment by LordKayBanks** [comment]
thank you. I should have thought of that.

persisted cache
docker run --gpus all -it -v ".:/app" -v whisper_cache:/cache ghcr.io/jim60105/whisperx:no_model -- --model large-v2 --language en --output_format srt audio.mp3
